name: audio_in_app
description: A Flutter plugin for playing audio files. Ideal for games or applications with sound.
version: 2.0.0
homepage: https://github.com/Cubel89/audio_in_app/tree/1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.0.0
  soundpool: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter