name: audio_in_app
description: A Flutter package for playing audio files. Ideal for games or applications with sound.
version: 4.2.0
homepage: https://github.com/Cubel89/audio_in_app
repository: https://github.com/Cubel89/audio_in_app

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_soloud: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter